import { execFileSync } from 'node:child_process';
import { createHandler } from '../server';

const root = new URL('../', import.meta.url).pathname;
const server = Bun.serve({ hostname: '127.0.0.1', port: 0, fetch: createHandler(root + 'public.routes.json') });
const session = 'sky-atlas-camera-' + process.pid;
execFileSync('agent-browser', ['--session', session, 'open', 'about:blank']);
const browserUrl = execFileSync('agent-browser', ['--session', session, 'get', 'cdp-url'], { encoding: 'utf8' }).trim();
const targets = await fetch('http://127.0.0.1:' + new URL(browserUrl).port + '/json/list').then(r => r.json());
const socket = new WebSocket(targets.find((t: any) => t.type === 'page').webSocketDebuggerUrl);
await new Promise<void>(resolve => socket.addEventListener('open', () => resolve(), { once: true }));
let id = 0;
const pending = new Map<number, any>();
const errors: string[] = [];
socket.addEventListener('message', event => {
  const message = JSON.parse(String(event.data));
  if (message.method === 'Runtime.exceptionThrown') errors.push(JSON.stringify(message.params.exceptionDetails));
  const request = pending.get(message.id);
  if (!request) return;
  pending.delete(message.id);
  clearTimeout(request.timer);
  message.error ? request.reject(new Error(JSON.stringify(message.error))) : request.resolve(message.result);
});
const send = (method: string, params = {}) => new Promise<any>((resolve, reject) => {
  const requestId = ++id;
  const timer = setTimeout(() => { pending.delete(requestId); reject(new Error('Timed out: ' + method)); }, 30000);
  pending.set(requestId, { resolve, reject, timer });
  socket.send(JSON.stringify({ id: requestId, method, params }));
});
const evaluate = async (expression: string) => {
  const result = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
  if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
  return result.result.value;
};
const pause = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
const results: string[] = [];
const check = (name: string, passed: boolean) => { if (!passed) throw new Error(name); results.push(name); };
const camera = () => evaluate("(()=>{const a=document.querySelector('[data-atlas]'); const m=new DOMMatrixReadOnly(getComputedStyle(document.querySelector('[data-atlas-world]')).transform);const b=a.getBoundingClientRect();return {x:m.e,y:m.f,z:m.a,width:b.width,height:b.height,top:b.top,left:b.left,selected:document.querySelector('.kingdom-node.is-active')?.dataset.nodeTitle};})()");
const click = (selector: string) => evaluate('document.querySelector(' + JSON.stringify(selector) + ').click()');
const move = (x: number, y: number) => send('Input.dispatchMouseEvent', { type: 'mouseMoved', x, y, button: 'left', buttons: 1 });
const mouse = (type: string, x: number, y: number) => send('Input.dispatchMouseEvent', { type, x, y, button: 'left', clickCount: 1, buttons: type === 'mousePressed' ? 1 : 0 });
const wheel = (x: number, y: number, deltaY: number, modifiers = 0) => send('Input.dispatchMouseEvent', { type: 'mouseWheel', x, y, deltaX: 0, deltaY, modifiers });
const key = (type: string, key: string, code: string) => send('Input.dispatchKeyEvent', { type, key, code });
const box = (selector: string) => evaluate('(()=>{const b=document.querySelector(' + JSON.stringify(selector) + ').getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};})()');
const metrics = async () => Object.fromEntries((await send('Performance.getMetrics')).metrics.map((m: any) => [m.name, m.value]));
const url = process.env.ATLAS_TEST_URL || 'http://127.0.0.1:' + server.port + '/#atlas';

try {
  await send('Runtime.enable');
  await send('Performance.enable');
  for (const mobile of [false, true]) {
    const label = mobile ? 'mobile' : 'desktop';
    await send('Emulation.setDeviceMetricsOverride', { width: mobile ? 390 : 1440, height: mobile ? 844 : 1000, deviceScaleFactor: 1, mobile });
    await send('Emulation.setTouchEmulationEnabled', { enabled: mobile, maxTouchPoints: 5 });
    await send('Page.navigate', { url: 'about:blank' });
    await send('Page.navigate', { url });
    await pause(1100);
    const regressions = await evaluate(await Bun.file(root + 'tests/atlas-interaction.browser.js').text());
    console.log(label, 'existing checks:', regressions.passed);
    results.push(...regressions.checks.map((name: string) => label + ': ' + name));
    await send('Page.navigate', { url });
    await pause(200);
    await send('Page.reload', { ignoreCache: true });
    await pause(800);
    const start = await camera();
    const anchor = { x: start.width * .38, y: start.height * .42 };
    await wheel(anchor.x, start.top + anchor.y, -60);
    await pause(90);
    const zoomed = await camera();
    check(label + ': plain wheel zooms without a modifier', zoomed.z > start.z);
    check(label + ': cursor stays anchored in world coordinates', Math.abs((anchor.x - start.x) / start.z - (anchor.x - zoomed.x) / zoomed.z) < .1 && Math.abs((anchor.y - start.y) / start.z - (anchor.y - zoomed.y) / zoomed.z) < .1);
    await pause(250);
    check(label + ': zoom has no trailing animation', Math.abs((await camera()).z - zoomed.z) < .00001);
    await click('[data-atlas-explore]'); await pause(350);
    const art = await box('.kingdom-node.is-active [data-atlas-select]');
    const x = art.x + art.w / 2, y = art.y + art.h / 2;
    const beforeDrag = await camera();
    await mouse('mousePressed', x, y);
    for (let i = 1; i <= 8; i++) { await move(x + i * 12, y + i * 5); await pause(16); }
    const dragged = await camera();
    check(label + ': dragging artwork tracks the pointer', Math.abs(dragged.x - beforeDrag.x - 96) < 2 && Math.abs(dragged.y - beforeDrag.y - 40) < 2);
    await mouse('mouseReleased', x + 96, y + 40);
    await pause(140);
    const gliding = await camera();
    check(label + ': drag release has a short glide', gliding.x > dragged.x + 3 && gliding.x < dragged.x + 210);
    check(label + ': dragging does not activate a kingdom', gliding.selected === beforeDrag.selected && !await evaluate("!!document.querySelector('.kingdom-node.is-arrived')"));
    await mouse('mousePressed', start.width * .5, start.top + start.height * .8);
    const interrupted = await camera();
    await pause(200);
    check(label + ': touching the map stops momentum immediately', Math.abs((await camera()).x - interrupted.x) < .1);
    await mouse('mouseReleased', start.width * .5, start.top + start.height * .8);
    await pause(400);
    await evaluate("document.querySelector('[data-atlas]').focus()");
    const keyStart = await camera();
    await key('keyDown', 'd', 'KeyD'); await pause(180);
    const keyDuring = await camera(); await pause(180);
    const keyEnd = await camera();
    await key('keyUp', 'd', 'KeyD');
    check(label + ': holding a key moves continuously', keyDuring.x < keyStart.x - 40 && keyEnd.x < keyDuring.x - 40);
    const released = await camera(); await pause(180);
    check(label + ': releasing movement key stops the camera', Math.abs((await camera()).x - released.x) < .1);
    check(label + ': exploring retains selected kingdom', (await camera()).selected === keyStart.selected);
    await click('[data-atlas-reset]'); await pause(320);
    const mini = await box('[data-atlas-minimap] svg');
    const mx = mini.x + mini.w * .4, my = mini.y + mini.h * .45;
    await mouse('mousePressed', mx, my); await pause(50);
    await move(mx + mini.w * .2, my); await pause(80);
    const miniDuring = await camera();
    await move(mx + mini.w * .3, my + mini.h * .1); await pause(80);
    const miniEnd = await camera();
    await mouse('mouseReleased', mx + mini.w * .3, my + mini.h * .1);
    check(label + ': mini-map continuously scrubs the camera', miniEnd.x < miniDuring.x - 100 && miniEnd.y < miniDuring.y - 80);
    await click('[data-atlas-explore]'); await pause(350);
    const artClick = await box('.kingdom-node.is-active [data-atlas-select]');
    await mouse('mousePressed', artClick.x + artClick.w / 2, artClick.y + artClick.h / 2);
    await mouse('mouseReleased', artClick.x + artClick.w / 2, artClick.y + artClick.h / 2);
    await pause(400);
    check(label + ': ordinary artwork click still focuses and arrives', await evaluate("!!document.querySelector('.kingdom-node.is-active.is-arrived')"));
    if (mobile) {
      await click('[data-atlas-explore]'); await pause(350);
      const before = await camera();
      const cy = before.top + before.height * .5;
      const touch = (type: string, points: any[]) => send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([id, x, y]) => ({ id, x, y, radiusX: 3, radiusY: 3, force: 1 })) });
      await touch('touchStart', [[1, 135, cy], [2, 255, cy]]);
      for (let i = 1; i <= 5; i++) { await touch('touchMove', [[1, 135 - i * 6, cy], [2, 255 + i * 6, cy]]); await pause(20); }
      const pinched = await camera();
      check('mobile: native two-finger pinch changes map zoom', Math.abs(pinched.z / before.z - 1.5) < .02);
      check('mobile: pinch midpoint remains anchored', Math.abs((195 - before.x) / before.z - (195 - pinched.x) / pinched.z) < 1);
      await touch('touchEnd', [[2, 285, cy]]);
      await touch('touchMove', [[1, 135, cy + 20]]); await pause(50);
      const resumed = await camera();
      check('mobile: lifting one finger resumes pan without a jump', Math.abs(resumed.x - pinched.x - 30) < 2 && Math.abs(resumed.y - pinched.y - 20) < 2);
      await touch('touchCancel', []); await pause(160);
      check('mobile: cancelled gesture stops cleanly', Math.abs((await camera()).x - resumed.x) < .1);
      await click('[data-atlas-explore]'); await pause(400);
      const tapArt = await box('.kingdom-node.is-active [data-atlas-select]');
      await touch('touchStart', [[3, tapArt.x + tapArt.w / 2, tapArt.y + tapArt.h / 2]]);
      await touch('touchEnd', []); await pause(400);
      check('mobile: touch tap still focuses kingdom artwork', await evaluate("!!document.querySelector('.kingdom-node.is-active.is-arrived')"));
    }
    await click('[data-atlas-explore]'); await pause(500);
    await evaluate("document.querySelector('[data-atlas]').focus()");
    const metricStart = await metrics();
    await key('keyDown', 'd', 'KeyD'); await pause(1000); await key('keyUp', 'd', 'KeyD');
    const metricEnd = await metrics();
    const layouts = metricEnd.LayoutCount - metricStart.LayoutCount;
    console.log(label, 'one-second continuous pan layout count:', layouts);
    check(label + ': camera pan avoids per-frame layout', layouts < 12);
    await click('[data-atlas-explore]'); await pause(350);
    const shot = await send('Page.captureScreenshot', { format: 'png' });
    await Bun.write(root + '_scratch/atlas-game-camera-' + label + '.png', Buffer.from(shot.data, 'base64'));
  }
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
  await send('Page.navigate', { url: 'about:blank' });
  await send('Page.navigate', { url }); await pause(800);
  await click('[data-atlas-next]');
  check('reduced motion: navigation completes without animation', !await evaluate("document.querySelector('[data-atlas]').classList.contains('is-zooming')"));
  check('no browser exceptions', errors.length === 0);
  console.log(JSON.stringify({ passed: results.length, checks: results }, null, 2));
} finally {
  if (errors.length) console.error('Browser errors:', errors);
  socket.close();
  server.stop();
  execFileSync('agent-browser', ['--session', session, 'close']);
}
